### ISSUE TITLE
basket in redux

### ISSUE THREAD

**Issue by VanoAkofashvili** [VanoAkofashvili/e-comm#12]
რიდაქსში ბასკეტი ცალკე რატო გააკეთე? cartActions და cartReducer გვაქვს... მაგ ფაილებშივე დაწერა უფრო ლოგიკური არ იქნებოდა?

**Comment by shotius** [comment]
თავიდან მანდ დავწერე სადაც ამბობ მარა მერე წაშლის ექშენიც რომ ემატებოდა ვიფიქრე უკეთესი იქნებოდა ცალკე ყოფილიყო, დიდი ფაილი გამოდიოდა ორივე ერთად, თან სხვა url  დან მოაქვს მონაცემები

**Comment by shotius** [comment]
და კიდე, basket api  ზე მონაცემები ხომ არ შეგისწორებია?  
მე მჭირდება 
 - id
 - userId
 -  პროდუქტის დანარჩენი ყველა ველი, ისე რომ ობიექტი nested  არ იყოს

**Comment by VanoAkofashvili** [comment]
> და კიდე, basket api  ზე მონაცემები ხომ არ შეგისწორებია?  
> მე მჭირდება 
>  - id
>  - userId
>  -  პროდუქტის დანარჩენი ყველა ველი, ისე რომ ობიექტი nested  არ იყოს

id დავამატე მხოლოდ, userIdსაც გავასწორებ... პროდუქტის  დანარჩენი ინფო nestingის გარეშე როგორ? ერთ ობიექტში რომ იყოს ყველაფერი? და არა product: ფროფერთის შიგნით?

**Comment by shotius** [comment]
> id დავამატე მხოლოდ, userIdსაც გავასწორებ... პროდუქტის დანარჩენი ინფო nestingის გარეშე როგორ? ერთ ობიექტში რომ იყოს ყველაფერი? და არა product: ფროფერთის შიგნით?

- კი product პროფერთის გარეშე

**Comment by VanoAkofashvili** [comment]
გავასწორე
