### ISSUE TITLE
basket

### ISSUE THREAD

**Issue by VanoAkofashvili** [VanoAkofashvili/e-comm#13]
სხვადასხვა იუზერით შესვლის დროს ყველას ერთი და იგივე პროდუქტი უჩანს, current იუზერის პროდუქტები არ მოდის კალათის გვერდზე

**Comment by shotius** [comment]
შევასწორე

**Comment by VanoAkofashvili** [comment]
basket-ში პროდუქტის რაოდენობის გაზრდის დროს ფასი არ იმატებს, ასევე ფასს რაც აჩვენებს დაამრგვალე თუარა მთელი ათწილადი როცა ჯდება გადის card-დან

**Comment by shotius** [comment]
ეგეც გავასწორე ფუნქცია არ მქონდა დაწერილი,  არ დამიფუშია ოღონდ

**Comment by shotius** [comment]
შეგიძლია დახურო
