### ISSUE TITLE
search 

### ISSUE THREAD

**Issue by shotius** [VanoAkofashvili/e-comm#14]
search გვაქ ჰედერში და ჰედერი ყველგანაა, როგორც მთავარ, ისე დეტალურ და კალათის გვერძე.
კითხვა:
 - როგორ მუშაობს ძებნა?
 1. ყველა გვერძე შესაბამის მონაცემებს იპოვის 
 2. არ აქვს რომელ გვერძე იქნება, იპოვის შესამის პროდუქტს

**Comment by VanoAkofashvili** [comment]
მნიშვნელობა არ აქვს რომელ გვერდზე იქნება, რასაც მოძებნის იმას იპოვის... ლეპტოპის გვერდზე რომ იყოს და სმარტფონი მოძებნოს უნდა იპოვოს რათქმაუნდა

**Comment by shotius** [comment]
> მნიშვნელობა არ აქვს რომელ გვერდზე იქნება, რასაც მოძებნის იმას იპოვის... ლეპტოპის გვერდზე რომ იყოს და სმარტფონი მოძებნოს უნდა იპოვოს რათქმაუნდა

და როგორ გამოიტანოს? მთავარ გვერძე გადაგაგდოს და შედეგი განახოს?

**Comment by VanoAkofashvili** [comment]
ჩემი აზრით თავისი გვერდი უნდა
