### ISSUE TITLE
adding in the basket

### ISSUE THREAD

**Issue by shotius** [VanoAkofashvili/e-comm#16]
- ბასკეტში დამატება არ ხდება იუზერის აიდის შემოწმების მეშვეობით
- ნოთიფიქეიშენი ძაან დიდი ხანი გრძელდება 3 წამი საკმარისი იქნება

**Comment by shotius** [comment]
და კიდე label როგორ დავუმატო issue -ს ? :დდდდ

**Comment by VanoAkofashvili** [comment]
1) done
2) 2 წამი დავაყენე
3) მარჯვენივ Labelს აწერია და მანდ დააჭირე
