### ISSUE TITLE
product cards

### ISSUE THREAD

**Issue by shotius** [VanoAkofashvili/e-comm#22]
პროდუქტის ქარდებს ყველგან ვიყენებთ,მთავარზეც, კატეგორიებშიც და ძებნაშიც shared  ფოლდერში ხომ არ ჩგვეგდო და მაგის css გარეთ src ფაილში გაგვეტანა?

**Comment by shotius** [comment]
- Spinner კომპონენტი შეიტა shared -ში ვებშტორმით
 - basket  და  search  შეცვალე Basket  და Search - ით

**Comment by VanoAkofashvili** [comment]
Done
